import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import './assets/colors.scss';
import { Menu } from "./components/menu";

const roboto = Roboto({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['cyrillic','latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <div className="max-w-[480px] w-full mx-auto">
        {children}
      

        <Menu />
   </div>
      </body>
    </html>
  );
}
